priority: 10
---
- model: &model !LateFusionNetwork { shared_weights: false }
---
- !ConfigVarTrainDatasetTrain { _tag: '!DepthImageCoupleDatasetIter' }
- !ConfigVarTrainDatasetTest { _tag: '!DepthImageCoupleDataset' }
- !ConfigVarEvalDatasetTrain { _tag: '!DepthImageCoupleDataset', name: Evaluation DepthImageCoupleDataset }
- !ConfigVarEvalDatasetTest { _tag: '!DepthImageCoupleDataset', name: Evaluation DepthImageCoupleDataset }
